# Site settings
title: Thang's Blog | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "https://benthunder.github.io"
author:
  name: "Lê Đình Thắng"
  email: "ledinhthang102@gmail.com"
  url: "https://benthunder.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
